### ISSUE TITLE
Weird Bug when running algorithm on full dna segments

### ISSUE THREAD

**Issue by damianoda96** [damianoda96/SequenceComparison#1]
Experiencing some weird output when running alignment on full dna lengths, aligned segment is larger that the beginning length of t, should be shorter, not sure where this is coming from

**Comment by tjp77** [comment]
Hmm weird. I'll start start looking into it now too.

**Comment by tjp77** [comment]
Finding the gaps right at least, compared to the BLAST output. If anything they should be equal sized at most since there's one gap in each side...

**Comment by tjp77** [comment]
Ok, the alignment isn't actually coming out longer then one of the starting sequences, it's the length of the shortest of the two, but a space got added in the start somehow. Adding in strip() of final 'best' values now.

**Comment by damianoda96** [comment]
Okay awesome, now we just have to sift through and find where the mutations
between the two are occurring

**Comment by tjp77** [comment]
I've been comparing our output to BLAST's result for the two sequences. After adding the stripping, checking the initial sequence lengths, checking the gap count, and comparing the two ends, it looks like we have the same exact output. We are getting the full things aligned due to so many similarities that they outweigh the differences so it doesn't hit 0 anywhere in trackback. The length statistics at the end are still going to show the alignment 1 more than the length of the shortest of the two sequences, but that's actually fine, because each side of the final alignment has a gap, those adding + 1 to the length, which matches the BLAST output.

**Comment by tjp77** [comment]
You want to finish the indel count, and I'll start on the other two mutation types? (I figured I could work on the majority since you've done a bit more so far)

I'll probably also work on a function for printing the alignment strands to file in a way that's more readable than the small space smooshed console output.

**Comment by damianoda96** [comment]
Yea that's perfect, I'll get a comparison going between blast and ours for
indel, thanks for help with the bug!

**Comment by tjp77** [comment]
Cool. Adding in one general analyze_alignment_mutations function, this will call separate functions to find each of the mutation types and print the results. That way everything is separated and we each know what part that other is working in to simplify things. Can combine anything that would be better that way after.
